[package]
name = "lb-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
http-body-util = "0.1.2"
hyper = { version="1.4.1", features = ["full"] }
hyper-util = { version = "0.1.6", features = ["full"] }
tokio = { version = "1.39.2", features = ["full"] }
